spring:
  datasource:
    username: ${RDB_USERNAME:postgres}
    url: ${RDB_URL:jdbc:postgresql://localhost:5432/dorumdorum}
    password: ${RDB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  key: ${JWT_KEY:fdsafdsafdsafdsafdsafdsafdsafdsafdsafdsafda}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION:900}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION:1209600}
  cookie:
    secure: false

logging:
  policy:
    include-stack-trace: true
  level:
    com.project.dorumdorum: DEBUG
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

firebase:
  service-account:
    path: ${FIREBASE_SERVICE_ACCOUNT_PATH:src/main/resources/firebase/dorumdorum-9ce75-firebase-adminsdk-fbsvc-8d66c0dccb.json}
