spring:
  datasource:
    hikari:
      maximum-pool-size: 16
      minimum-idle: 4
      connection-timeout: 5000
      validation-timeout: 1000
      idle-timeout: 600000
      max-lifetime: 1700000

    username: ${RDB_USERNAME}
    url: ${RDB_URL}
    password: ${RDB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

jwt:
  key: ${JWT_KEY}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}
  cookie:
    same-site: None

logging:
  policy:
    include-stack-trace: false
  level:
    root: INFO
    com.project.dorumdorum: INFO
    org.hibernate.SQL: WARN
    org.springframework: WARN

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

firebase:
  service-account:
    path: ${FIREBASE_SERVICE_ACCOUNT_PATH}

alert:
  discord:
    webhook-url: ${DISCORD_WEBHOOK}
